"Reset" button for chats
faetalize/zodiac pull request #5
Opened 2023-12-26 19:14 UTC by LyubomirT

As stated in #4, a reset button will improve the overall experience and let the user wipe the chat without having to refresh the page. This Pull Request implements the button. You can find it close to the message box (on the left side), it looks like this:

![image](https://github.com/faetalize/zodiac/assets/127299159/e51a56e1-23ec-43d2-af9e-8dc0c8137d68)

It uses an icon from Material Icons Outlined. To wipe the chat, it removes all messages from the `messagesContainer` and clears the `chatHistory` variable, while re-setting the chat to the default one in the `chat` variable as well.

Here's a little preview that shows how the button works:

https://github.com/faetalize/zodiac/assets/127299159/5c173126-e65c-40e6-b275-d2a07b304fbe

Please let me know if you have any questions or if you'd like anything to be changed!

2023-12-26 20:12 UTC, faetalize requested changes
Great start.
Please implement the following changes so we can get your PR merged asap!

- the logic for resetting the chat should be outside the `run` function. simply create const references to the elements you wish to modify at the top of your event handler.
- Emptying the messages container is enough. as the `run` function recreates a chatHistory object everytime it is called, using the contents of the container.
Something like:
```js
const resetChatButton = document.querySelector("#btn-reset-chat");
const messageContainer = document.querySelector(".message-container");
//reset chat button (async)
resetChatButton.addEventListener("click", () => {
        //remove all messages
        messageContainer.innerHTML = "";
});
```

2023-12-26 20:35 UTC, LyubomirT commented
Alright, thanks for pointing me in the right direction. I'll get to implement the changes when I return home (might take a little while since I'm a bit busy at the moment).

2023-12-27 07:21 UTC, faetalize commented
Alternatively, I can commit those changes for you (on your forked repo). They will be included in this PR.

2023-12-27 07:38 UTC, LyubomirT commented
> Alternatively, I can commit those changes for you (on your forked repo). They will be included in this PR.

There is no need to do that. I've just created a new commit with the requested changes.

2023-12-27 07:57 UTC, faetalize requested changes
This is way more efficient, however:
* `resetChatButton` and `messageContainer` are defined inside the run() function and that's a problem. your event handler doesnt have access to those elements.

You can remedy this by extracting the `const messageContainer = document.querySelector(".message-container");` and `const resetChatButton = document.querySelector("#btn-reset-chat");` declarations from the run() function, and placing them above your event handler, like this.

```js

async function run(){
    //..
    const messageContainer = document.querySelector(".message-container"); //delete this
    //..
    const resetChatButton = document.querySelector("#btn-reset-chat"); //delete this
    //..
}

//place them here
const messageContainer = document.querySelector(".message-container");
const resetChatButton = document.querySelector("#btn-reset-chat");
resetChatButton.addEventListener("click", () => {
        messageContainer.innerHTML = "";
});
```

2023-12-27 08:03 UTC, faetalize requested changes
one more! (messageContainer too)

2023-12-27 08:54 UTC, faetalize approved these changes

2023-12-27 08:55 UTC, merged